### ISSUE TITLE
error when closing zmq socket: `Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:261)`

### ISSUE THREAD

**Issue by OttoAllmendinger** [0xB10C/bademeister-go#11]
There is an error about 1 in 5 times the socket gets closed:

```
Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:261)
SIGABRT: abort
PC=0x7f10153c0f25 m=3 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f10153c0f25
stack: frame={sp:0x7f101252e800, fp:0x0} stack=[0x7f1011d2f048,0x7f101252ec48)
00007f101252e700:  00000000ffffffff  0000000000000000 
00007f101252e710:  00007f101556fbc8  00007f101560b000 
00007f101252e720:  0000000000000000  0000000000000000 
00007f101252e730:  0000000000000001  000000500009d91c 
00007f101252e740:  00000000ffffffff  0000000000000000 
00007f101252e750:  00007f101556fc28  0000000000a2b078 
00007f101252e760:  00007f101252f678  ffffffffffffffff 
00007f101252e770:  000000c000045000  0000000000000001 
00007f101252e780:  0000000000000200  00007f1015650eb7 
00007f101252e790:  0000000000000005  0000000000000000 
00007f101252e7a0:  000000c000044bf0  00007f101556fbc8 
00007f101252e7b0:  00007f101252ebb0  00007f10156578ee 
00007f101252e7c0:  00007f101252f678  000000c00025a038 
00007f101252e7d0:  000000c00025a030  000000000000000d 
00007f101252e7e0:  00007f1000004b80  000000c00007f980 
00007f101252e7f0:  0000000000000000  00007f10156578ee 
00007f101252e800: <0000000000000000  000000c000044c30 
00007f101252e810:  000000c000044bc0  0000ffff00001fa0 
00007f101252e820:  000000c00025c000  000000c00007f980 
00007f101252e830:  0000000000000000  0000000000a41a20 
00007f101252e840:  0000000000000000  0000000000000000 
00007f101252e850:  00000000008aa288  0000ffff00001fa0 
00007f101252e860:  0000000000000000  0000000000000000 
00007f101252e870:  0000000000000000  0000000000000000 
00007f101252e880:  fffffffe7fffffff  ffffffffffffffff 
00007f101252e890:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8a0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8b0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8c0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8d0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8e0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8f0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f10153c0f25
stack: frame={sp:0x7f101252e800, fp:0x0} stack=[0x7f1011d2f048,0x7f101252ec48)
00007f101252e700:  00000000ffffffff  0000000000000000 
00007f101252e710:  00007f101556fbc8  00007f101560b000 
00007f101252e720:  0000000000000000  0000000000000000 
00007f101252e730:  0000000000000001  000000500009d91c 
00007f101252e740:  00000000ffffffff  0000000000000000 
00007f101252e750:  00007f101556fc28  0000000000a2b078 
00007f101252e760:  00007f101252f678  ffffffffffffffff 
00007f101252e770:  000000c000045000  0000000000000001 
00007f101252e780:  0000000000000200  00007f1015650eb7 
00007f101252e790:  0000000000000005  0000000000000000 
00007f101252e7a0:  000000c000044bf0  00007f101556fbc8 
00007f101252e7b0:  00007f101252ebb0  00007f10156578ee 
00007f101252e7c0:  00007f101252f678  000000c00025a038 
00007f101252e7d0:  000000c00025a030  000000000000000d 
00007f101252e7e0:  00007f1000004b80  000000c00007f980 
00007f101252e7f0:  0000000000000000  00007f10156578ee 
00007f101252e800: <0000000000000000  000000c000044c30 
00007f101252e810:  000000c000044bc0  0000ffff00001fa0 
00007f101252e820:  000000c00025c000  000000c00007f980 
00007f101252e830:  0000000000000000  0000000000a41a20 
00007f101252e840:  0000000000000000  0000000000000000 
00007f101252e850:  00000000008aa288  0000ffff00001fa0 
00007f101252e860:  0000000000000000  0000000000000000 
00007f101252e870:  0000000000000000  0000000000000000 
00007f101252e880:  fffffffe7fffffff  ffffffffffffffff 
00007f101252e890:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8a0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8b0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8c0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8d0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8e0:  ffffffffffffffff  ffffffffffffffff 
00007f101252e8f0:  ffffffffffffffff  ffffffffffffffff 

goroutine 41 [syscall]:
runtime.cgocall(0x6fa670, 0xc000044be8, 0x6fa620)
	/usr/lib/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000044bb8 sp=0xc000044b80 pc=0x40755b
github.com/pebbe/zmq4._C2func_zmq_msg_recv(0xc0001f2300, 0x7f1000004b80, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:428 +0x55 fp=0xc000044be8 sp=0xc000044bb8 pc=0x569c45
github.com/pebbe/zmq4.(*Socket).RecvBytes.func1(0xc0001f2300, 0xc0001fa6f0, 0x0, 0x0, 0x24, 0x40)
	/home/otto/godev/pkg/mod/github.com/pebbe/zmq4@v1.0.0/zmq4.go:964 +0x75 fp=0xc000044c30 sp=0xc000044be8 pc=0x56c625
github.com/pebbe/zmq4.(*Socket).RecvBytes(0xc0001fa6f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/otto/godev/pkg/mod/github.com/pebbe/zmq4@v1.0.0/zmq4.go:964 +0x168 fp=0xc000044ce0 sp=0xc000044c30 pc=0x56bc68
github.com/pebbe/zmq4.(*Socket).RecvMessageBytes(0xc0001fa6f0, 0x0, 0x0, 0x0, 0x0, 0x8, 0x0)
	/home/otto/godev/pkg/mod/github.com/pebbe/zmq4@v1.0.0/utils.go:141 +0x80 fp=0xc000044d68 sp=0xc000044ce0 pc=0x5695e0
github.com/0xb10c/bademeister-go/src/zmqsubscriber.NewZMQSubscriber.func1(0xc0001fa6f0, 0xc00020a3c0, 0xc00020a420)
	/home/otto/src/bademeister-go/src/zmqsubscriber/zmqsubscriber.go:80 +0x76 fp=0xc000044fc8 sp=0xc000044d68 pc=0x6f9406
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000044fd0 sp=0xc000044fc8 pc=0x462851
created by github.com/0xb10c/bademeister-go/src/zmqsubscriber.NewZMQSubscriber
	/home/otto/src/bademeister-go/src/zmqsubscriber/zmqsubscriber.go:77 +0x3ba

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000188100, 0x7caef5, 0x11, 0x7e2330, 0x486036)
	/usr/lib/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc000188000)
	/usr/lib/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc000188000, 0xc000177dc0)
	/usr/lib/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc0000a46a0, 0xa2cb70, 0x1, 0x1, 0x0)
	/usr/lib/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc00017e080, 0x0)
	/usr/lib/go/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:44 +0x135

goroutine 19 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x229a1, 0xc0001e7c80, 0x1000004, 0x0, 0x0, 0xc0001e7cb0, 0x432bf1, 0x7e2c38)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc0000901b0, 0x407bc5, 0xc000015500, 0xc0001e7d68)
	/usr/lib/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc0000901b0, 0x4919a5, 0xc0000901c4, 0x2)
	/usr/lib/go/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(...)
	/usr/lib/go/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc00015e580, 0x83fa60, 0x8334e0)
	/usr/lib/go/src/os/exec/exec.go:501 +0x60
github.com/0xb10c/bademeister-go/src/test.(*TestEnv).Quit(0xc0001e7f30)
	/home/otto/src/bademeister-go/src/test/testenv.go:143 +0x75
github.com/0xb10c/bademeister-go/src/zmqsubscriber.TestZMQSubscriber(0xc000188100)
	/home/otto/src/bademeister-go/src/zmqsubscriber/zmqsubscriber_test.go:50 +0x3fe
testing.tRunner(0xc000188100, 0x7e2330)
	/usr/lib/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:960 +0x350

goroutine 5 [select]:
github.com/btcsuite/btcd/rpcclient.(*Client).sendPostHandler(0xc0001ba0a0)
	/home/otto/godev/pkg/mod/github.com/btcsuite/btcd@v0.20.0-beta/rpcclient/infrastructure.go:736 +0xd9
created by github.com/btcsuite/btcd/rpcclient.(*Client).start
	/home/otto/godev/pkg/mod/github.com/btcsuite/btcd@v0.20.0-beta/rpcclient/infrastructure.go:1029 +0x10f

goroutine 43 [chan receive]:
github.com/0xb10c/bademeister-go/src/zmqsubscriber.TestZMQSubscriber.func3(0xc0001ee190, 0xc000208720)
	/home/otto/src/bademeister-go/src/zmqsubscriber/zmqsubscriber_test.go:37 +0x82
created by github.com/0xb10c/bademeister-go/src/zmqsubscriber.TestZMQSubscriber
	/home/otto/src/bademeister-go/src/zmqsubscriber/zmqsubscriber_test.go:36 +0x223

goroutine 42 [chan receive]:
github.com/0xb10c/bademeister-go/src/zmqsubscriber.TestZMQSubscriber.func2(0xc0001ee190, 0xc000208700)
	/home/otto/src/bademeister-go/src/zmqsubscriber/zmqsubscriber_test.go:29 +0x7f
created by github.com/0xb10c/bademeister-go/src/zmqsubscriber.TestZMQSubscriber
	/home/otto/src/bademeister-go/src/zmqsubscriber/zmqsubscriber_test.go:28 +0x1d2

rax    0x0
rbx    0x7f101252f700
rcx    0x7f10153c0f25
rdx    0x0
rdi    0x2
rsi    0x7f101252e800
rbp    0x7f101252eac0
rsp    0x7f101252e800
r8     0x0
r9     0x7f101252e800
r10    0x8
r11    0x246
r12    0x0
r13    0x7f10000052d8
r14    0xffffffff
r15    0x7f101252f678
rip    0x7f10153c0f25
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

Process finished with exit code 1
```

**Comment by OttoAllmendinger** [comment]
Added workaround in https://github.com/0xB10C/bademeister-go/commit/b519765626c1b437973ec08ca54b7e9358b70d2d: we `Recv()` with a timeout of 1s and  `Close()` instead of `Recv()` if cancellation flag is set. A bit inelegant but the crash is gone.
